export const ActionTypes = {
    SET_PRODUCT: "SET_PRODUCT",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    ADD_PRODUCT_TO_CART: "ADD_PRODUCT_TO_CART",
    REMOVE_PRODUCT_TO_CART: "REMOVE_PRODUCT_TO_CART",
}